name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Crear carpeta temp
        run: mkdir -p temp

      - name: Extraer shiny rank
        run: python shinyrank.py

      - name: Extraer destacados
        run: python destacados.py

      - name: Extraer legendarios
        run: python legendarios.py

      - name: Extraer shinys
        run: python shinys.py

      - name: Extraer noticias
        run: python noticias.py

      - name: Move JSON files to working directory
        run: |
          mv temp/rankshiny.json ./
          mv temp/destacados.json ./
          mv temp/raid_hour.json ./
          mv temp/shinys.json ./
          mv temp/noticias.json ./

      - name: Commit JSON Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git switch --orphan data
          git add rankshiny.json destacados.json raid_hour.json shinys.json noticias.json
          git commit -m "Datos actualizados 🤖🍺"

      - name: Push Data Branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: data
          force: true