name: Update Raid Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-raid-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install requests
        pip install beautifulsoup4

    - name: Run Python Script
      run: python bosses.py

    - name: Move JSON File to Working Directory
      run: mv temp/raid_data_by_level.json ./

    - name: Commit and Push JSON to Main
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        git add raid_data_by_level.json
        git commit -m "Update raid data" || true  # Esto generar치 una confirmaci칩n incluso si no hay cambios.
        git push || true  # Esto empujar치 la confirmaci칩n, reemplazando el archivo JSON existente.

    - name: Remove Temp Folder
      run: rm -r temp
